### ISSUE TITLE
Onboarding Tracked for KServe

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#32]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation
**--Company Sponsor (Full Legal Name):** KServe Project Community 
**--Project Sponsor Contact:** Animesh Singh <singhan@us.ibm.com>
**--Technical Contact:** [Animesh Singh](mailto:singhan@us.ibm.com) and [Dan Sun](mailto:dsun20@bloomberg.net)
**--Legal Contact:**
**--TAC Sponsor:** Ibrahim Haddad
**--TAC Approval Date:** 11/18/2021
**--Project in SFDC:**
**--Project License:** Apache 2.0 
**--Project Presentation:** [Link to deck as pdf](https://docs.google.com/presentation/d/1klvbeUsP9wkUgohhuyQemGOdQxvGlqF43DQ8JNR0qGs/edit?usp=sharing)
**--Project Proposal per LF AI & Data:** [Proposal URL](https://github.com/lfai/proposing-projects/blob/master/proposals/kserve.md)
**--Project Artwork:** https://github.com/lfai/artwork/tree/main/projects/kserve 

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The technical charter is tailored for LF AI & Data - Copy is to be created for each project - The technical charter will always need the following information dropped in place: the short name of the project (where [Community Name] appears); a short mission statement following the "The mission of the project is to..." convention; and confirmation of the specific licenses in Section 7 for code and/or data (many projects will not need data and this subjection regarding data licensing in those cases can be removed)
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The trademark assignment agreement is also tailored for LF AI & Data - Copy is to be created for each project - As for the trademark agreement, we will entertain changes from companies contributing projects but we ask that the following be made clear to project sponsors: the contribution agreement was prepared to be a balanced agreement -- A large number of our members sign this as drafted; and extensive comments and revisions to the agreement will involve time which will slow down a project's start with LF AI & Data
- [x] (Tech/ED) Verify [CII Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) link and passing status - https://bestpractices.coreinfrastructure.org/en/projects/6643

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation
- [x] (Tech/ED) Post project logos to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder]
- [x] (Tech/ED) Domain name confirmation // ongoing via IT-23414
- [x] (Tech/ED) Project website confirmation // If no website exists (as noted above), request a new website creation via Creative Services Jira ticket (Include request for project lead to be added as authorized user for Word Press for future website updates, requires -name/email of authorized user) 
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org // code already in own GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project
- [x] (Tech/ED) Add sponsor company to landscape page 

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist 
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any --n/a
- [x] (PM) Set up project Zoom account (Requires new LF AI & Data email alias for new account set up) - Upon request only per onboarding email info provided to project --project did not request Zoom account
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project --pending request from project --project did not request wiki space
- [x] (PM) Request project to be added to [LFX Insights ](https://insights.lfx.linuxfoundation.org/) via Jira Service Desk for request --(https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-7870#) --follow up in April when onboarding is resumed --marked as resolved on 09/27/2022, tracked in LF AI & Data Trello Board for Insights v.2 release on 09/30/2022.
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) - Project lead will need to make request, request on LFX Portal under 'Secure My Project' section (top right) -- pending LF ID form lead
- [x] (PM) Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) --n/a

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic)
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required (https://jira.linuxfoundation.org/browse/LP-8124)
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker] (https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) --draft in progress, confirm with Animesh before publishing on February 24 @ 9 AM EST
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker] --added to tracker (https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable --no accounts included in proposal
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) -- February 24 @ 9 AM EST
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation]  (https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) --no accounts included in proposal

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through Steve W. for all projects via ticket at https://www.linuxfoundation.org/export/ (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects --(https://legaljira.linuxfoundation.org/servicedesk/customer/portal/1/LR-889) --followed up on 01.19.2022 --see Mike Dolan's comment dated 01/24, followed up on 02/15 --marked as resolved on 10/03/2022, tracked in LF AI & Data Trello Board for legal follow up w/ Jeff Shapiro
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by ErinThacker** [comment]
@animeshsingh -  in order to onboard the project to LFX Security, you will need to install a bot as administrator of the GitHub repo. To do this, we need your LF ID. Can you share that with us? If you don't have an LF ID, you can register for one here: https://identity.linuxfoundation.org/

Thanks and let me know if you have any questions.

**Comment by yuzisun** [comment]
@ErinThacker Animesh is on vacation, can you use my LFID?

**Comment by ErinThacker** [comment]
@yuzisun - I will check. Thanks!

**Comment by jzcardoso** [comment]
@ErinThacker Can you please circle back on open items in this issue? Thanks!

**Comment by ErinThacker** [comment]
@yuzisun - we can use your LF ID, just as long as you have admin rights on the repo. Please forward as soon as you can.

**Comment by ErinThacker** [comment]
@animeshsingh & @yuzisun - can you please provide an LF ID so we can secure the project in LFX? Thanks!

**Comment by animeshsingh** [comment]
Its my email @ErinThacker 

singhan@us.ibm.com

**Comment by jzcardoso** [comment]
@ibrahimhaddad and @ErinThacker - Looks like this onboarding is also close to done. Can you please take a look at open items?

**Comment by ErinThacker** [comment]
@ibrahimhaddad & @jzcardoso - I followed up again on the legal support ticket for an update on export control filings. I'm working on finding out when Insights projects onboarding will resume.

**Comment by ErinThacker** [comment]
@ibrahimhaddad - can you give me an update on these items: Licensing (FOSSology scan & known contributions/dependencies), Contribution (CII Badge status), Project Assets (website confirmation & project website tracking)

**Comment by ErinThacker** [comment]
No authorized user has been provided from project in regards to project website access. Follow-ups were completed, will close out issue and note single item pending in internal Trello board filed under backlog. Impact to project will be no back-up or continuity support from LF staff for account.
