### ISSUE TITLE
Graduating Flyte

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#33]
The following tasks are required to complete for projects which have moved from the Incubation level to Graduate level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:** Flyte
**--Proposal URL:** https://docs.google.com/presentation/d/1iP2-IczEH7MksTSrFwQ9Wg_NYCgRxbnJ2uBj5AwihRM/edit#slide=id.gf828797e74_0_72
**--Graduation Date:** 12 07 2021
**--Technical Lead Contact:** Ketan Umar - ketan@union.ai

**ITEMS TO COMPLETE**
- [x] Include TAC Graduation item for voting in next Governing Board meeting
- [x] Update project flag to Graduated on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=graduated) (will auto update Graduated Projects on LF AI & Data website)
- [x] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Graduate level + Update 'Learn More' section with Graduation date --pending CS ticket (https://jira.linuxfoundation.org/browse/LP-8127)
- [x] Update [TAC wiki](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=7733341#TechnicalAdvisoryCouncil(TAC)-MemberRepresentatives) with Graduated project + project lead info for TAC voting representation
- [x] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Graduate flag
- [x] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Graduate flag, if wiki space is used
- [x] Add project lead to [tac-private mailing list](https://lists.lfaidata.foundation/g/tac-private/members) for voting representatives
- [x] Add project lead to [outreach-committee mailing list](https://lists.lfaidata.foundation/g/outreach-committee/members) for observer role inclusion
- [x] Send [welcome/info note](https://docs.google.com/document/d/138IK-pNccyFO11DzVN7tRkUaplzoNIgFJfPvnCzkREo/edit) to project lead
- [x] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination
- [x] Create CS ticket to update LF AI & Data Timeline with new technical project under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub](https://github.com/lfai/presentations/tree/master/Timeline) --https://jira.linuxfoundation.org/browse/LP-8130
- [x] Update [LF AI & Data Getting Involved Deck](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit?ts=5c5b8268#slide=id.p1) - Project slide + Landscape slide --project slide updated, waiting on updated landscape
- [x] Update [LF AI & Data Overview Deck ](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit#slide=id.p2)- Timeline slide --
- [x] Update LF AI & Data Getting Involved + Overview Decks on [LF AI & Data GitHub](https://github.com/lfai/presentations)

**Comment by ErinThacker** [comment]
@ibrahimhaddad - can you please update the project to graduate in the landscape?

**Comment by jzcardoso** [comment]
@ErinThacker Can you please follow up on the pending items for this issue? You may need to ping Ibrahim on the Landscape update.
